export const CONTACT_INFO = {
  nom: 'ABASSI BTP',
  formeJuridique: 'SAS',
  titre: 'Entreprise de BTP - Gros œuvre et rénovation',
  adresse: '7 Esplanade Solange Fernex, 67400 Illkirch-Graffenstaden',
  telephone: '07 68 24 59 95',
  telephoneLien: '0768245995',
  email: 'Abassyan67@gmail.com',
  horaires: 'Du lundi au vendredi, de 8h00 à 18h00',
  mapUrl: 'https://www.google.com/maps/search/?api=1&query=7+Esplanade+Solange+Fernex+67400+Illkirch-Graffenstaden',
  rcs: 'RCS Strasbourg 100 492 750',
  dateCreation: '2026',
  bio: 'Entreprise de BTP spécialisée dans les travaux de gros œuvre, rénovation et aménagement extérieur. Nous intervenons en maçonnerie générale, ravalement de façades, isolation, bardage, terrassement et finitions.',
  zoneIntervention: 'Illkirch et région Alsace',
} as const
