export const SERVICES = [
  {
    id: 'maconnerie',
    nom: 'MAÇONNERIE GÉNÉRALE',
    description: 'Gros œuvre, fondations, murs porteurs',
    fullDescription: 'Notre équipe de maçons qualifiés réalise tous vos travaux de maçonnerie générale, du gros œuvre aux finitions. Nous prenons en charge la construction de fondations solides et durables, l\'édification de murs porteurs, la création d\'ouvertures et bien plus encore. Avec une expertise approfondie dans le domaine, nous garantissons des réalisations conformes aux normes en vigueur et adaptées à vos besoins spécifiques. Que ce soit pour une construction neuve, une extension ou une rénovation, nous vous accompagnons dans la réalisation de votre projet avec professionnalisme et rigueur.',
    image: 'https://images.unsplash.com/photo-1597476374792-c9e5bfdca9ff?w=600&h=400&fit=crop',
  },
  {
    id: 'ravalement',
    nom: 'RAVALEMENT DE FAÇADES',
    description: 'Rénovation et embellissement de façades',
    fullDescription: 'Le ravalement de façade est une opération essentielle pour préserver et embellir votre bâtiment. Notre service comprend le nettoyage, la réparation et la protection de vos façades. Nous utilisons des techniques modernes et des matériaux de qualité pour redonner à vos murs extérieurs leur éclat d\'origine tout en assurant leur protection contre les intempéries et le temps. Nous intervenons sur tous types de façades : crépi, pierre, brique, enduit... et respectons scrupuleusement les réglementations locales et les délais imposés.',
    image: 'https://images.unsplash.com/photo-1632778149955-e80f8ceca2e8?w=600&h=400&fit=crop',
  },
  {
    id: 'isolation',
    nom: 'ISOLATION',
    description: 'Isolation thermique et phonique',
    fullDescription: 'L\'isolation est un investissement rentable qui améliore votre confort tout en réduisant vos factures énergétiques. Nous proposons des solutions d\'isolation thermique et phonique adaptées à chaque situation : isolation par l\'intérieur ou l\'extérieur, combles, murs, sols. Notre expertise nous permet de vous conseiller sur les meilleures techniques et matériaux selon votre projet et votre budget. Nous travaillons avec des isolants performants et respectueux de l\'environnement pour garantir une efficacité optimale et durable.',
    image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=600&h=400&fit=crop',
  },
  {
    id: 'bardage',
    nom: 'BARDAGE',
    description: 'Habillage et protection des façades',
    fullDescription: 'Le bardage est une solution esthétique et performante pour habiller et protéger vos façades. Nous installons différents types de bardages : bois, composite, PVC, métal, selon vos préférences et le style architectural de votre bâtiment. Au-delà de son aspect décoratif, le bardage offre une protection supplémentaire contre les intempéries et peut être associé à une isolation extérieure pour améliorer les performances énergétiques de votre habitation. Nos équipes réalisent une pose soignée garantissant la durabilité et l\'étanchéité de votre bardage.',
    image: 'https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=600&h=400&fit=crop',
  },
  {
    id: 'terrassement',
    nom: 'TERRASSEMENT',
    description: 'Préparation de terrains et VRD',
    fullDescription: 'Le terrassement est la première étape cruciale de tout projet de construction. Nous réalisons l\'ensemble des travaux de terrassement : décapage, excavation, nivellement, remblaiement et compactage. Notre équipe dispose du matériel nécessaire pour intervenir sur tous types de terrains et de projets, des petites excavations aux grands chantiers. Nous prenons également en charge les travaux de VRD (Voirie et Réseaux Divers) : création de tranchées pour réseaux, pose de canalisations, aménagement de voies d\'accès.',
    image: 'https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?w=600&h=400&fit=crop',
  },
  {
    id: 'amenagement',
    nom: 'AMÉNAGEMENTS EXTÉRIEURS',
    description: 'Terrasses, allées, espaces extérieurs',
    fullDescription: 'Sublimez vos espaces extérieurs avec nos solutions d\'aménagement personnalisées. Nous créons des terrasses, allées, cours et jardins qui allient fonctionnalité et esthétique. Que vous souhaitiez une terrasse en bois, pierre naturelle, béton décoratif ou carrelage, nous vous proposons des réalisations sur mesure adaptées à vos goûts et à l\'architecture de votre propriété. Nos aménagements extérieurs sont conçus pour durer et résister aux contraintes climatiques tout en valorisant votre bien immobilier.',
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&h=400&fit=crop',
  },
  {
    id: 'peinture',
    nom: 'PEINTURE & REVÊTEMENTS',
    description: 'Finitions intérieures et extérieures',
    fullDescription: 'Les finitions font toute la différence dans la qualité d\'un projet. Notre équipe de peintres professionnels réalise tous vos travaux de peinture intérieure et extérieure avec soin et précision. Nous vous conseillons sur le choix des couleurs et des revêtements les plus adaptés à vos besoins et à votre style. Peinture décorative, enduits, papiers peints, revêtements muraux... nous maîtrisons toutes les techniques pour sublimer vos espaces et leur donner une finition impeccable qui durera dans le temps.',
    image: 'https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=600&h=400&fit=crop',
  },
  {
    id: 'renovation',
    nom: 'RÉNOVATION',
    description: 'Rénovation complète de bâtiments',
    fullDescription: 'La rénovation complète d\'un bâtiment nécessite une coordination parfaite de tous les corps de métier. Nous gérons votre projet de A à Z : diagnostic initial, conception, coordination des travaux et suivi jusqu\'à la livraison. Que vous souhaitiez rénover une maison ancienne, moderniser un appartement ou réhabiliter un local professionnel, nous mettons notre savoir-faire à votre service pour transformer votre bien selon vos attentes, tout en respectant votre budget et les délais convenus. Nous veillons à préserver le cachet d\'origine tout en apportant confort et modernité.',
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&h=400&fit=crop',
  },
] as const
